backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/images
public_folder: ../../static/images

collections:
  - name: "song"
    label: "Song"
    folder: "content/songs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "song"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Lyrics", name: "body", widget: "markdown", required: false}
      - {label: "Details", name: "details", widget: "markdown", required: false}
      - {label: "Score", name: "score", widget: "file", required: false}
      - {label: "Finch", name: "finch", widget: "file", required: false}
      - {label: "Heron", name: "heron", widget: "file", required: false}
      - {label: "Raven", name: "raven", widget: "file", required: false}
